name: 'hydrastream'
version: '1.0.0'
config-version: 2

profile: 'hydrastream'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ drop_flink_tables() }}"

models:
  hydrastream:
    +materialized: table # In Flink context, this often maps to CREATE TABLE
