apiVersion: v1
kind: Service
metadata:
  name: flink-gateway-proxy
  namespace: default
  labels:
    app: flink-gateway-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flink-gateway-proxy
